enum GameState {
    PLAYER_1_IDLE,
    PLAYER_1_WAITING,
    PLAYER_1_DISPLAY_PLAYER,
    PLAYER_1_MOVING,
    PLAYER_2_MOVING,
    PLAYER_1_WIN,
    PLAYER_2_WIN,
    PLAYER_1_QUIT,
    PLAYER_2_QUIT,
    PLAYER_TIE
};